# Generated by ./update.sh - do not update manually!
{ fetchurl}:

{
  x86_64-linux = {
    version = "0.0.22-alpha";
    src = fetchurl {
      url = "https://updater.osmium.chat/Osmium-0.0.22-alpha-x64.tar.gz";
      hash = "sha256-iuO0CFFqhx38JcdxXE8Vd5TCetheMOFecDFCqCvO2Xs=";
    };
  };
  aarch64-linux = {
    version = "0.0.22-alpha";
    src = fetchurl {
      url = "https://updater.osmium.chat/Osmium-0.0.22-alpha-arm64.tar.gz";
      hash = "sha256-dQPzXy0aXoyuP659pwcxnSrsBqFMYB2nEDVCj11R52A=";
    };
  };
  x86_64-darwin = {
    version = "0.0.20-alpha";
    src = fetchurl {
      url = "https://updater.osmium.chat/Osmium-0.0.20-alpha-x64.zip";
      hash = "sha256-EgECoopO4TkKyeTYNYaFlHVdn7MfENLvbxNyl6UPPOY=";
    };
  };
  aarch64-darwin = {
    version = "0.0.20-alpha";
    src = fetchurl {
      url = "https://updater.osmium.chat/Osmium-0.0.20-alpha-arm64.zip";
      hash = "sha256-Tk+JZJqNRJ6xSY5M4pzIEhXDY5FXgfQpUEsvSSQ3yrE=";
    };
  };
}
