#! /usr/bin/env nix-shell
#! nix-shell -i bash --pure --keep GITHUB_TOKEN -p nix curl yq cacert nix-prefetch-git

set -euxo pipefail

linux_x86_64=$(curl https://updater.osmium.chat/alpha-linux.yml)
linux_aarch64=$(curl https://updater.osmium.chat/alpha-linux-arm64.yml)
darwin=$(curl https://updater.osmium.chat/alpha-mac.yml)

linux_x86_64_version=$(echo "$linux_x86_64" | yq -r .version)
linux_aarch64_version=$(echo "$linux_aarch64" | yq -r .version)
darwin_version=$(echo "$darwin" | yq -r .version)

linux_x86_64_url="https://updater.osmium.chat/Osmium-${linux_x86_64_version}-x64.tar.gz"
linux_aarch64_url="https://updater.osmium.chat/Osmium-${linux_aarch64_version}-arm64.tar.gz"
darwin_x86_64_url="https://updater.osmium.chat/Osmium-${darwin_version}-x64.zip"
darwin_aarch64_url="https://updater.osmium.chat/Osmium-${darwin_version}-arm64.zip"

linux_x86_64_hash=$(nix-prefetch-url $linux_x86_64_url)
linux_aarch64_hash=$(nix-prefetch-url $linux_aarch64_url)
darwin_x86_64_hash=$(nix-prefetch-url $darwin_x86_64_url)
darwin_aarch64_hash=$(nix-prefetch-url $darwin_aarch64_url)

linux_x86_64_hash=$(nix --extra-experimental-features nix-command hash convert --to sri --hash-algo sha256 "$linux_x86_64_hash")
linux_aarch64_hash=$(nix --extra-experimental-features nix-command hash convert --to sri --hash-algo sha256 "$linux_aarch64_hash")
darwin_x86_64_hash=$(nix --extra-experimental-features nix-command hash convert --to sri --hash-algo sha256 "$darwin_x86_64_hash")
darwin_aarch64_hash=$(nix --extra-experimental-features nix-command hash convert --to sri --hash-algo sha256 "$darwin_aarch64_hash")

cat >sources.nix <<EOF
# Generated by ./update.sh - do not update manually!
{ fetchurl}:

{
  x86_64-linux = {
    version = "$linux_x86_64_version";
    src = fetchurl {
      url = "$linux_x86_64_url";
      hash = "$linux_x86_64_hash";
    };
  };
  aarch64-linux = {
    version = "$linux_aarch64_version";
    src = fetchurl {
      url = "$linux_aarch64_url";
      hash = "$linux_aarch64_hash";
    };
  };
  x86_64-darwin = {
    version = "$darwin_version";
    src = fetchurl {
      url = "$darwin_x86_64_url";
      hash = "$darwin_x86_64_hash";
    };
  };
  aarch64-darwin = {
    version = "$darwin_version";
    src = fetchurl {
      url = "$darwin_aarch64_url";
      hash = "$darwin_aarch64_hash";
    };
  };
}
EOF
